import { type AtomicElement } from "@bio-sim/event-schemas";

type ElementRecord = AtomicElement & { group: number; period: number; category: string };

const elements: ElementRecord[] = [
  {
    element: "Hydrogen",
    symbol: "H",
    atomicNumber: 1,
    atomicMass: 1.008,
    electronConfiguration: "1s1",
    electronegativity: 2.2,
    oxidationStates: [1, -1],
    reductionPotential: 0.0,
    group: 1,
    period: 1,
    category: "nonmetal",
  },
  {
    element: "Lithium",
    symbol: "Li",
    atomicNumber: 3,
    atomicMass: 6.94,
    electronConfiguration: "[He] 2s1",
    electronegativity: 0.98,
    oxidationStates: [1],
    reductionPotential: -3.04,
    group: 1,
    period: 2,
    category: "alkali metal",
  },
  {
    element: "Carbon",
    symbol: "C",
    atomicNumber: 6,
    atomicMass: 12.011,
    electronConfiguration: "[He] 2s2 2p2",
    electronegativity: 2.55,
    oxidationStates: [-4, 4, 2, -2],
    reductionPotential: -0.25,
    group: 14,
    period: 2,
    category: "nonmetal",
  },
  {
    element: "Nitrogen",
    symbol: "N",
    atomicNumber: 7,
    atomicMass: 14.007,
    electronConfiguration: "[He] 2s2 2p3",
    electronegativity: 3.04,
    oxidationStates: [-3, -2, -1, 1, 2, 3, 4, 5],
    reductionPotential: -0.28,
    group: 15,
    period: 2,
    category: "nonmetal",
  },
  {
    element: "Oxygen",
    symbol: "O",
    atomicNumber: 8,
    atomicMass: 15.999,
    electronConfiguration: "[He] 2s2 2p4",
    electronegativity: 3.44,
    oxidationStates: [-2, -1, 0, 1, 2],
    reductionPotential: 0.0,
    group: 16,
    period: 2,
    category: "nonmetal",
  },
  {
    element: "Phosphorus",
    symbol: "P",
    atomicNumber: 15,
    atomicMass: 30.974,
    electronConfiguration: "[Ne] 3s2 3p3",
    electronegativity: 2.19,
    oxidationStates: [-3, -2, -1, 1, 2, 3, 4, 5],
    reductionPotential: -0.28,
    group: 15,
    period: 3,
    category: "nonmetal",
  },
  {
    element: "Sulfur",
    symbol: "S",
    atomicNumber: 16,
    atomicMass: 32.06,
    electronConfiguration: "[Ne] 3s2 3p4",
    electronegativity: 2.58,
    oxidationStates: [-2, -1, 0, 1, 2, 4, 6],
    reductionPotential: 0.14,
    group: 16,
    period: 3,
    category: "nonmetal",
  },
  {
    element: "Sodium",
    symbol: "Na",
    atomicNumber: 11,
    atomicMass: 22.990,
    electronConfiguration: "[Ne] 3s1",
    electronegativity: 0.93,
    oxidationStates: [1],
    reductionPotential: -2.71,
    group: 1,
    period: 3,
    category: "alkali metal",
  },
  {
    element: "Magnesium",
    symbol: "Mg",
    atomicNumber: 12,
    atomicMass: 24.305,
    electronConfiguration: "[Ne] 3s2",
    electronegativity: 1.31,
    oxidationStates: [2],
    reductionPotential: -2.37,
    group: 2,
    period: 3,
    category: "alkaline earth metal",
  },
  {
    element: "Potassium",
    symbol: "K",
    atomicNumber: 19,
    atomicMass: 39.098,
    electronConfiguration: "[Ar] 4s1",
    electronegativity: 0.82,
    oxidationStates: [1],
    reductionPotential: -2.93,
    group: 1,
    period: 4,
    category: "alkali metal",
  },
  {
    element: "Calcium",
    symbol: "Ca",
    atomicNumber: 20,
    atomicMass: 40.078,
    electronConfiguration: "[Ar] 4s2",
    electronegativity: 1.0,
    oxidationStates: [2],
    reductionPotential: -2.87,
    group: 2,
    period: 4,
    category: "alkaline earth metal",
  },
  {
    element: "Chromium",
    symbol: "Cr",
    atomicNumber: 24,
    atomicMass: 51.996,
    electronConfiguration: "[Ar] 3d5 4s1",
    electronegativity: 1.66,
    oxidationStates: [-2, -1, 1, 2, 3, 4, 5, 6],
    reductionPotential: -0.41,
    group: 6,
    period: 4,
    category: "transition metal",
  },
  {
    element: "Manganese",
    symbol: "Mn",
    atomicNumber: 25,
    atomicMass: 54.938,
    electronConfiguration: "[Ar] 3d5 4s2",
    electronegativity: 1.55,
    oxidationStates: [-3, -2, -1, 1, 2, 3, 4, 5, 6, 7],
    reductionPotential: -1.18,
    group: 7,
    period: 4,
    category: "transition metal",
  },
  {
    element: "Iron",
    symbol: "Fe",
    atomicNumber: 26,
    atomicMass: 55.845,
    electronConfiguration: "[Ar] 3d6 4s2",
    electronegativity: 1.83,
    oxidationStates: [-2, -1, 1, 2, 3, 4, 5, 6],
    reductionPotential: -0.44,
    group: 8,
    period: 4,
    category: "transition metal",
  },
  {
    element: "Cobalt",
    symbol: "Co",
    atomicNumber: 27,
    atomicMass: 58.933,
    electronConfiguration: "[Ar] 3d7 4s2",
    electronegativity: 1.88,
    oxidationStates: [-1, 0, 1, 2, 3, 4, 5],
    reductionPotential: -0.28,
    group: 9,
    period: 4,
    category: "transition metal",
  },
  {
    element: "Nickel",
    symbol: "Ni",
    atomicNumber: 28,
    atomicMass: 58.693,
    electronConfiguration: "[Ar] 3d8 4s2",
    electronegativity: 1.91,
    oxidationStates: [-1, 0, 1, 2, 3, 4],
    reductionPotential: -0.25,
    group: 10,
    period: 4,
    category: "transition metal",
  },
  {
    element: "Copper",
    symbol: "Cu",
    atomicNumber: 29,
    atomicMass: 63.546,
    electronConfiguration: "[Ar] 3d10 4s1",
    electronegativity: 1.9,
    oxidationStates: [1, 2, 3, 4, 5],
    reductionPotential: 0.34,
    group: 11,
    period: 4,
    category: "transition metal",
  },
  {
    element: "Zinc",
    symbol: "Zn",
    atomicNumber: 30,
    atomicMass: 65.38,
    electronConfiguration: "[Ar] 3d10 4s2",
    electronegativity: 1.65,
    oxidationStates: [2],
    reductionPotential: -0.76,
    group: 12,
    period: 4,
    category: "transition metal",
  },
  {
    element: "Selenium",
    symbol: "Se",
    atomicNumber: 34,
    atomicMass: 78.971,
    electronConfiguration: "[Ar] 3d10 4s2 4p4",
    electronegativity: 2.55,
    oxidationStates: [-2, 2, 4, 6],
    reductionPotential: 0.74,
    group: 16,
    period: 4,
    category: "nonmetal",
  },
  {
    element: "Molybdenum",
    symbol: "Mo",
    atomicNumber: 42,
    atomicMass: 95.95,
    electronConfiguration: "[Kr] 4d5 5s1",
    electronegativity: 2.16,
    oxidationStates: [-2, -1, 0, 1, 2, 3, 4, 5, 6],
    reductionPotential: -0.2,
    group: 6,
    period: 5,
    category: "transition metal",
  },
];

const indexBySymbol = new Map(elements.map((element) => [element.symbol, element]));

export function listElements(): ElementRecord[] {
  return elements.slice();
}

export function getElementBySymbol(symbol: string): ElementRecord | undefined {
  return indexBySymbol.get(symbol);
}

export type { ElementRecord };
